language: csharp
mono: latest
dotnet: 5.0.401
solution: Game.sln
before_install:
   - wget https://packages.microsoft.com/config/ubuntu/21.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
   - sudo dpkg -i packages-microsoft-prod.deb
   - rm packages-microsoft-prod.deb
