name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      
    - name: Install dependencies
      run: make build
      
    - name: Run check
      run: make run
